import {clubSearchNames,isClub} from './club-identities.mjs?v=20260908-identities1';
import {STATUS,clubName,norm,safeURL,unknown,deduplicate,filterTransfers,counts,isNewTransfer} from './data-core.mjs?v=20260909-new1';
const $=s=>document.querySelector(s), esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const read=(k,d)=>{try{return JSON.parse(localStorage.getItem(k))??d}catch{return d}};
const write=(k,v)=>{localStorage.setItem(k,JSON.stringify(v))};
let media={clubs:{},players:{}},raw=[],items=[],sources=[],meta={},shown=50,view='transfers',filters={},teamSearch='';
const params=()=>new URLSearchParams(location.search);
function route(){const p=params();view=['teams','sources'].includes(p.get('view'))?p.get('view'):'transfers';filters=Object.fromEntries(['q','team','league','pos','status','from','until'].map(k=>[k,p.get(k)||'']));filters.team=clubName(filters.team);shown=50;render()}
function url(f={},v='transfers'){const p=new URLSearchParams({view:v});for(const [k,val] of Object.entries(f))if(val)p.set(k,val);return '?'+p}
function navigate(href){history.pushState(null,'',href);route();window.scrollTo(0,0)}
function avatar(name,type='club',imageURL=''){const m=media[type==='club'?'clubs':'players'][norm(name)];const src=safeURL(imageURL||m?.url);return '<span class="media-avatar '+type+'-avatar" aria-hidden="true"><span>'+esc(initials(name))+'</span>'+(src?'<img src="'+esc(src)+'" alt="" loading="lazy" decoding="async" referrerpolicy="no-referrer">':'')+'</span>'}
const teamLink=t=>unknown(t)?'<span class="muted">Not reported</span>':'<a class="club-link" href="'+esc(url({team:t}))+'">'+avatar(t)+'<span>'+esc(t)+'</span></a>';
const date=d=>new Date(d+'T12:00:00Z').toLocaleDateString('en-GB',{day:'numeric',month:'short',year:'numeric'});
const initials=s=>s.split(/\s+/).map(w=>w[0]).slice(0,2).join('').toUpperCase();
function toast(text){$('#toast').textContent=text;$('#toast').classList.remove('hidden');setTimeout(()=>$('#toast').classList.add('hidden'),4000)}
function rebuild(){const edits=read('euroball_local_edits',{}),adds=read('euroball_local_adds',[]);items=deduplicate([...raw,...(Array.isArray(adds)?adds:[])].map(t=>{const patch=edits[t.id]||t.alias_ids?.map(id=>edits[id]).find(Boolean);return patch?{...t,...patch,_local:true,verified_at:null}:t}));}
async function load(){try{const results=await Promise.all(['transfers_all.json','sources.json','data-review.json','media.json'].map(async path=>{const r=await fetch(path+'?v='+Date.now(),{cache:'no-cache'});if(!r.ok){if(path==='media.json')return {clubs:{},players:{}};throw Error(path)}return r.json()}));[raw,sources,meta,media]=results;raw=Array.isArray(raw)?raw:raw.items;rebuild();route()}catch{$('#main').innerHTML='<div class="empty"><h1>The feed could not load</h1><p>Please check your connection and try again.</p><button id="retry">Try again</button></div>';$('#retry').onclick=load}}
function options(values,current,all){return `<option value="">${all}</option>`+values.map(v=>`<option ${v===current?'selected':''} value="${esc(v)}">${esc(v==='coach'?'Coach':v)}</option>`).join('')}
function controls(){return `<div class="filter-top"><label class="search-wrap"><span aria-hidden="true">⌕</span><input id="query" type="search" aria-label="Search players or teams" placeholder="Search players or teams…" value="${esc(filters.q)}"></label><label class="desktop-filter"><span class="field-label">Competition</span><select data-filter="league">${options([...new Set(items.flatMap(t=>t.leagues))].sort(),filters.league,'All leagues')}</select></label><label class="desktop-filter"><span class="field-label">Position</span><select data-filter="pos">${options(['PG','SG','SF','PF','C','G','F','coach'],filters.pos,'All positions')}</select></label><button class="desktop-filter" data-action="filters">Dates & filters</button><button class="mobile-filter" data-action="filters">☷ Filters</button></div><div id="statuses" class="status-bar" aria-label="Transfer status"></div><div class="filter-summary"><span id="result-count" role="status" aria-live="polite"></span><button class="text-button" data-action="clear">Clear filters</button></div>`}
function render(){document.querySelectorAll('[data-view]').forEach(a=>{if(a.dataset.view===view)a.setAttribute('aria-current','page');else a.removeAttribute('aria-current')});if(view==='transfers')renderTransfers();else if(view==='teams')renderTeams();else renderSources()}
function renderTransfers(){const isTeam=!!filters.team;$('#main').innerHTML=`<section class="intro">${isTeam?'<a class="back-link" href="?view=teams">← All teams</a>':''}<h1>${isTeam?esc(filters.team):'<span class="desktop-title">European basketball transfers</span><span class="mobile-title" style="display:none">Transfers</span>'}</h1><p class="subtitle">${isTeam?'Arrivals, departures and the latest reports.':'Every move. One clear view.'}</p><p class="freshness">2026/27 season · Latest source review <time>${esc(meta.reviewed_on?date(meta.reviewed_on):'not available')}</time></p></section><div class="page-grid"><section aria-label="Transfer feed">${controls()}<div class="feed-heading"><h2>${isTeam?'Team activity':'Latest moves'}</h2><small>Newest first · Dates labeled</small></div><div class="table-shell"><table class="transfer-table"><caption class="sr-only">Transfer news, newest first</caption><colgroup><col class="col-date"><col class="col-player"><col class="col-club"><col class="col-club"><col class="col-status"><col class="col-source"></colgroup><thead><tr><th scope="col">Date</th><th scope="col">Player / coach</th><th scope="col">From</th><th scope="col">To</th><th scope="col">Status / league</th><th scope="col">Source</th></tr></thead><tbody id="feed"></tbody></table></div><button id="more" class="load-more">Load 50 more transfers ↓</button></section><aside class="aside"><div class="side-card"><h3>Browse teams</h3><input id="side-search" type="search" placeholder="Find a team…" aria-label="Find a team"><div id="side-teams"></div><a class="source-link" href="?view=teams">View all teams →</a></div><div class="side-card"><h3>The transfer desk</h3><p>Signings, extensions, departures and rumors across European basketball.</p><p>Open a player for contract details and source history. Rumors stay clearly marked.</p><p>Reviewed entries carry a check date. Older records retain their original sources and may need another check.</p><a class="source-link" href="?view=sources">Explore our sources →</a></div></aside></div>`;updateFeed();sideTeams();$('#query').oninput=e=>{filters.q=e.target.value;updateFilterURL();shown=50;updateFeed()};document.querySelectorAll('[data-filter]').forEach(s=>s.onchange=e=>{filters[s.dataset.filter]=e.target.value;updateFilterURL();shown=50;updateFeed()});$('#side-search').oninput=e=>sideTeams(e.target.value);$('#more').onclick=()=>{shown+=50;updateFeed()}}
function updateFilterURL(){history.replaceState(null,'',url(filters))}
function card(t){const fresh=isNewTransfer(t);return `<tr class="transfer-row${fresh?' is-new':''}"><td class="row-date"><time datetime="${t.date}">${new Date(t.date+'T12:00:00Z').toLocaleDateString('en-GB',{day:'numeric',month:'short'})}</time><small>${t.date_basis==='report_date'?'Reported · ':''}${t.date.slice(0,4)}</small></td><td class="row-player"><div class="person">${avatar(t.player,'player',t.player_image||t.photo_url)}<div><button class="player-name" data-record="${esc(t.id)}">${esc(t.player)}</button>${fresh?'<span class="new-badge" title="Added to the tracker in the last 72 hours">New</span>':''}<small>${esc(t.pos==='coach'?'Coach':unknown(t.pos)?'—':t.pos)}${t._local?' · Local edit':''}</small></div></div></td><td class="row-from" data-label="From">${teamLink(t.from)}</td><td class="row-to" data-label="To">${teamLink(t.to)}</td><td class="row-status"><span class="badge ${t.status}">${t.status==='signed'?'✓ ':''}${STATUS[t.status]}</span><small>${esc(t.league||'League not reported')}</small></td><td class="row-source">${t.source_url?`<a class="source-link" href="${esc(t.source_url)}" target="_blank" rel="noopener noreferrer">${esc(t.source_name||'Read source')} ↗</a>`:'<small>Unavailable</small>'}</td></tr>`}

function updateFeed(){const scoped=filterTransfers(items,{...filters,status:''}),c=counts(scoped),result=filterTransfers(items,filters);$('#statuses').innerHTML=[['','All',c.all],...Object.entries(STATUS).map(([k,v])=>[k,v,c[k]])].map(([key,label,n])=>`<button class="chip" data-status="${key}" aria-pressed="${filters.status===key}">${label}<span>${n}</span></button>`).join('');$('#result-count').textContent=`${result.length.toLocaleString()} ${result.length===1?'transfer':'transfers'}${result.filter(t=>isNewTransfer(t)).length?' · '+result.filter(t=>isNewTransfer(t)).length+' new in the last 72 hours':''}${filters.team?' · '+filters.team:''}${filters.league?' · '+filters.league:''}${filters.pos?' · '+(filters.pos==='coach'?'Coach':filters.pos):''}${filters.from?' · From '+filters.from:''}${filters.until?' · Through '+filters.until:''}`;$('#feed').innerHTML=result.length?result.slice(0,shown).map(card).join(''):'<tr><td colspan="6"><div class="empty"><h3>No transfers found</h3><p>Try another player, team or filter.</p><button data-action="clear">Clear filters</button></div></td></tr>';$('#more').classList.toggle('hidden',shown>=result.length)}
function teams(){return [...new Set(items.flatMap(t=>[t.from,t.to]).filter(isClub))].sort((a,b)=>a.localeCompare(b))}
function sideTeams(q=''){const list=q?teams().filter(t=>norm(clubSearchNames(t)).includes(norm(q))):['Real Madrid','Olympiacos','Dubai Basketball','Barcelona','Partizan Mozzart Bet Belgrade'];$('#side-teams').innerHTML=list.slice(0,5).map(t=>`<a class="team-mini" href="${esc(url({team:t}))}">${avatar(t)}${esc(t)}<span class="chevron">›</span></a>`).join('')||'<p>No matching teams.</p>'}
function renderTeams(){ $('#main').innerHTML='<div class="view-header"><h1>Teams</h1><p>Follow a club’s transfer activity. This is a news archive, not a current roster.</p></div><div class="page-tools"><input id="team-query" type="search" placeholder="Search teams…" aria-label="Search teams"></div><div id="team-list" class="teams-grid"></div>';const draw=q=>{const list=teams().filter(t=>norm(clubSearchNames(t)).includes(norm(q)));$('#team-list').innerHTML=list.map(t=>`<a class="team-card" href="${esc(url({team:t}))}">${avatar(t)}<h3>${esc(t)}</h3><p>${filterTransfers(items,{team:t}).length} transfer stories →</p></a>`).join('')||'<p>No teams found.</p>'};draw('');$('#team-query').oninput=e=>draw(e.target.value)}
function renderSources(){$('#main').innerHTML=`<div class="view-header"><h1>Our sources</h1><p>Official league news, club announcements and basketball reporting.</p><p class="freshness">Source review: ${esc(date(meta.reviewed_on))}. Some pages restrict access or show older indexed content; coverage is not exhaustive.</p><p class="freshness">Club crests and player portraits come from Euroleague Basketball, ABA League, national leagues, NBA and ScoutBasketball. <a href="media.json" target="_blank" rel="noopener noreferrer">View image credits</a>. Portraits may show a previous season’s uniform.</p></div><div class="page-tools"><input id="source-query" type="search" placeholder="Search sources or leagues…" aria-label="Search sources"><button id="source-export">Export sources JSON</button></div><div id="source-list" class="source-grid"></div>`;const draw=q=>$('#source-list').innerHTML=sources.filter(s=>norm([s.name,s.league].join(' ')).includes(norm(q))).map(s=>`<article class="source-card"><small>${esc(s.league||s.cat)}</small><h3>${esc(s.name)}</h3><a class="source-link" target="_blank" rel="noopener noreferrer" href="${esc(safeURL(s.url))}">Visit source ↗</a><p class="source-status">${esc(s.review_status||'Listed source; individual stories checked when added.')}</p></article>`).join('')||'<p>No sources found.</p>';draw('');$('#source-query').oninput=e=>draw(e.target.value);$('#source-export').onclick=()=>download(sources,'euroball-sources.json')}
function openDialog(html,id='dialog'){const d=$('#'+id);d.innerHTML=html;d.showModal();d.querySelector('[data-close]').onclick=()=>d.close()}
function head(title,id='dialog-title',portrait=''){const heading=`<h2 id="${id}">${esc(title)}</h2>`;return `<div class="dialog-head">${portrait?`<div class="dialog-person">${portrait}${heading}</div>`:heading}<button data-close aria-label="Close dialog">×</button></div>`}
function details(id){const t=items.find(t=>t.id===id);if(!t)return;openDialog(head(t.player,'dialog-title',avatar(t.player,'player',t.player_image||t.photo_url))+`<span class="badge ${t.status}">${STATUS[t.status]}</span><dl class="details-list"><dt>Announced</dt><dd>${date(t.date)}${t.date_basis==='report_date'?' (report date; announcement date unavailable)':''}</dd><dt>From</dt><dd>${teamLink(t.from)}</dd><dt>To</dt><dd>${teamLink(t.to)}</dd><dt>Contract</dt><dd>${esc(t.contract||'Not reported')}</dd><dt>Reviewed</dt><dd>${t.verified_at?date(t.verified_at):'Older entry · not rechecked in this update'}</dd></dl><p class="dialog-copy">${esc(t.summary||'Open the source for the full story.')}</p>${media.players[norm(t.player)]?'<p class="dialog-copy">Portrait: '+esc(media.players[norm(t.player)].provider)+' · '+esc(media.players[norm(t.player)].season||'Profile photo')+'. The uniform may represent a previous club.</p>':''}${[...new Map([{url:t.source_url,name:t.source_name},...(t.sources||[])].filter(s=>safeURL(s.url)).map(s=>[s.url,s])).values()].map(s=>`<p><a class="source-link" href="${esc(safeURL(s.url))}" target="_blank" rel="noopener noreferrer">${esc(s.name||'Read source')} ↗</a></p>`).join('')}${t.history?.length?'<div class="history"><h3>Earlier report</h3>'+t.history.map(h=>`<p class="dialog-copy">${esc(h.date)} · ${esc(STATUS[h.status]||h.status)}${safeURL(h.source_url)?` · <a href="${esc(h.source_url)}" target="_blank" rel="noopener noreferrer">Source ↗</a>`:''}</p>`).join('')+'</div>':''}<div class="dialog-actions"><button id="edit-record">Edit locally</button><button id="share-record">Copy story link</button></div>`);$('#edit-record').onclick=()=>{$('#dialog').close();edit(t)};$('#share-record').onclick=async()=>{try{await navigator.clipboard.writeText(new URL(url({q:t.player}),location.href).href);toast('Story link copied')}catch{toast('Copy the page address to share this story')}}}
function filterDialog(){openDialog(head('Filter transfers','filter-title')+`<form id="filter-form"><div class="form-grid"><label>Competition<select name="league">${options([...new Set(items.flatMap(t=>t.leagues))].sort(),filters.league,'All leagues')}</select></label><label>Position<select name="pos">${options(['PG','SG','SF','PF','C','G','F','coach'],filters.pos,'All positions')}</select></label><label>From date<input name="from" type="date" value="${esc(filters.from)}"></label><label>Through date<input name="until" type="date" value="${esc(filters.until)}"></label></div><div class="dialog-actions"><button class="primary">Apply filters</button><button type="button" id="reset-sheet">Reset filters</button></div></form>`,'filter-dialog');$('#filter-form').onsubmit=e=>{e.preventDefault();const f=Object.fromEntries(new FormData(e.target));if(f.from&&f.until&&f.from>f.until){toast('The start date must be before the end date');return}Object.assign(filters,f);$('#filter-dialog').close();updateFilterURL();renderTransfers()};$('#reset-sheet').onclick=()=>{$('#filter-dialog').close();navigate('?view=transfers')}}
function edit(t={}){const fields=[['player','Player or coach'],['from','From club'],['to','To club'],['league','League'],['pos','Position (PG, SG, SF, PF, C, coach)'],['contract','Contract'],['source_name','Source name'],['source_url','Source article URL']];openDialog(head(t.id?'Edit transfer locally':'Add a transfer locally')+`<p class="dialog-copy">Saved only in this browser. Export local changes to share or publish them.</p><form id="edit-form"><div class="form-grid">${fields.map(([k,label])=>`<label>${label}<input name="${k}" value="${esc(t[k]||'')}" ${k==='player'?'required':''} ${k==='source_url'?'type="url"':''}></label>`).join('')}<label>Announcement date<input type="date" name="date" required value="${esc(t.date||new Date().toISOString().slice(0,10))}"></label><label>Status<select name="status">${Object.entries(STATUS).map(([k,v])=>`<option value="${k}" ${t.status===k?'selected':''}>${v}</option>`).join('')}</select></label><label class="wide">Notes<textarea name="summary">${esc(t.summary||'')}</textarea></label></div><div class="dialog-actions"><button class="primary">Save locally</button></div></form>`);$('#edit-form').onsubmit=e=>{e.preventDefault();const patch=Object.fromEntries(new FormData(e.target));patch.player=patch.player.trim();if(!patch.player)return;try{if(t.id){const edits=read('euroball_local_edits',{});edits[t.id]=patch;write('euroball_local_edits',edits)}else{const adds=read('euroball_local_adds',[]);adds.push({...patch,id:'local-'+crypto.randomUUID(),_local:true});write('euroball_local_adds',adds)}rebuild();$('#dialog').close();render();toast('Saved in this browser')}catch{toast('Browser storage is unavailable. Changes were not saved.')}}}
function download(data,name){const link=document.createElement('a'),blob=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));link.href=blob;link.download=name;link.click();setTimeout(()=>URL.revokeObjectURL(blob),1000)}
document.addEventListener('click',e=>{const a=e.target.closest('a');if(a?.getAttribute('href')?.startsWith('?')&&!e.ctrlKey&&!e.metaKey){e.preventDefault();document.querySelectorAll('dialog[open]').forEach(d=>d.close());navigate(a.getAttribute('href'));return}const b=e.target.closest('button');if(!b)return;if(b.hasAttribute('data-status')){filters.status=b.dataset.status;shown=50;updateFilterURL();updateFeed()}if(b.dataset.record)details(b.dataset.record);if(b.dataset.action==='filters')filterDialog();if(b.dataset.action==='clear')navigate('?view=transfers')});
$('#add').onclick=()=>edit();$('#export-local').onclick=()=>download({edits:read('euroball_local_edits',{}),adds:read('euroball_local_adds',[])},'euroball-local-changes.json');$('#export-all').onclick=()=>download(items.map(({search,leagues,...t})=>t),'euroball-transfers.json');$('#refresh').onclick=()=>load();
const theme=read('euroball_theme','light');document.documentElement.dataset.theme=theme;$('#theme').onclick=()=>{const next=document.documentElement.dataset.theme==='dark'?'light':'dark';document.documentElement.dataset.theme=next;try{write('euroball_theme',next)}catch{}};window.addEventListener('popstate',route);load();

// Failed or blocked remote media falls back to initials without a broken-image icon.
document.addEventListener('error',e=>{if(e.target.matches?.('.media-avatar img'))e.target.remove()},true);
const sizeHeader=()=>document.documentElement.style.setProperty('--header-height',$('.topbar').getBoundingClientRect().height+'px');new ResizeObserver(sizeHeader).observe($('.topbar'));sizeHeader();
